language: php

php:
  - 5.3

mysql:
  database: entityreference_uuid
  username: root
  encoding: utf8

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # install drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.8.0
  - phpenv rehash

  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database entityreference_uuid'
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/entityreference_uuid --enable=simpletest entityreference_uuid

  # reference and enable entityreference_uuid in build site
  - ln -s $(readlink -e $(cd -)) entityreference_uuid/drupal/sites/all/modules/entityreference_uuid
  - cd entityreference_uuid/drupal
  - drush --yes pm-enable entityreference_uuid

  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script: drush test-run entityreference_uuid --uri=http://127.0.0.1:8080
