<?php

/**
 * @file
 * Add UUID column to entity reference.
 */

/**
 * Load the UUID behavior.
 *
 * CTools doesn't load all the plugins correctly upon installation, so we reset
 * the plugins cache, so our Entity reference behaviors will be used.
 * Apart of Calling ctools_get_plugins_reset() we also get all the entity
 * reference "behavior" plugins and load the class ourself.
 * This issue can be seen when executing simpleTests or enabling the module
 * via Drush.
 */
function entityreference_uuid_load_behavior() {
  ctools_include('plugins');
  ctools_get_plugins_reset();
  module_load_include('php', 'praise_general', 'entityreference/behavior/UuidEntityReferenceBehavior.class');
  ctools_get_plugins('entityreference', 'behavior');
}

/**
 * Implements hook_field_default_field_bases().
 */
function praise_general_field_default_field_bases() {
  entityreference_uuid_load_behavior();
}


/**
 * Implements hook_ctools_plugin_directory().
 */
function entityreference_uuid_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'entityreference/' . $plugin;
  }
}

/**
 * Implements hook_entity_presave().
 */
function entityreference_uuid_entity_presave($entity, $type) {
  if (!$field_name = variable_get('entityreference_uuid_field_name', 'field_uuid')) {
    // No UUID field name defined.
    return;
  }

  if (!variable_get('entityreference_uuid_set_uuid_on_presave', TRUE)) {
    // Admin turned off this option.
    return;
  }

  $wrapper = entity_metadata_wrapper($type, $entity);
  if (!isset($wrapper->{$field_name}) || $wrapper->{$field_name}->value()) {
    // Field doesn't exist, or UUID already exists.
    return;
  }

  $wrapper->{$field_name}->set(md5(rand()));
}